include: package:lints/recommended

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
  exclude:
    - build/**
    - .tmp_generated/**
