// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './subscriptions_post_request_body_add_invoice_items.dart';
import './subscriptions_post_request_body_application_fee_percent.dart';
import './subscriptions_post_request_body_automatic_tax.dart';
import './subscriptions_post_request_body_billing_thresholds.dart';
import './subscriptions_post_request_body_cancel_at.dart';
import './subscriptions_post_request_body_collection_method.dart';
import './subscriptions_post_request_body_default_tax_rates.dart';
import './subscriptions_post_request_body_discounts.dart';
import './subscriptions_post_request_body_invoice_settings.dart';
import './subscriptions_post_request_body_items.dart';
import './subscriptions_post_request_body_payment_behavior.dart';
import './subscriptions_post_request_body_payment_settings.dart';
import './subscriptions_post_request_body_pending_invoice_item_interval.dart';
import './subscriptions_post_request_body_proration_behavior.dart';
import './subscriptions_post_request_body_transfer_data.dart';
import './subscriptions_post_request_body_trial_end.dart';
import './subscriptions_post_request_body_trial_settings.dart';

/// auto generated
class SubscriptionsPostRequestBody implements Parsable {
  ///  A list of prices and quantities that will generate invoice items appended to the next invoice for this subscription. You may pass up to 20 items.
  Iterable<SubscriptionsPostRequestBodyAddInvoiceItems>? addInvoiceItems;

  ///  A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice total that will be transferred to the application owner's Stripe account. The request must be made by a platform account on a connected account in order to set an application fee percentage. For more information, see the application fees [documentation](https://stripe.com/docs/connect/subscriptions#collecting-fees-on-subscriptions).
  SubscriptionsPostRequestBodyApplicationFeePercent? applicationFeePercent;

  ///  Automatic tax settings for this subscription.
  SubscriptionsPostRequestBodyAutomaticTax? automaticTax;

  ///  A past timestamp to backdate the subscription's start date to. If set, the first invoice will contain line items for the timespan between the start date and the current time. Can be combined with trials and the billing cycle anchor.
  int? backdateStartDate;

  ///  A future timestamp in UTC format to anchor the subscription's [billing cycle](https://docs.stripe.com/subscriptions/billing-cycle). The anchor is the reference point that aligns future billing cycle dates. It sets the day of week for `week` intervals, the day of month for `month` and `year` intervals, and the month of year for `year` intervals.
  int? billingCycleAnchor;

  ///  Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period. When updating, pass an empty string to remove previously-defined thresholds.
  SubscriptionsPostRequestBodyBillingThresholds? billingThresholds;

  ///  A timestamp at which the subscription should cancel. If set to a date before the current period ends, this will cause a proration if prorations have been enabled using `proration_behavior`. If set during a future period, this will always cause a proration for that period.
  SubscriptionsPostRequestBodyCancelAt? cancelAt;

  ///  Indicate whether this subscription should cancel at the end of the current period (`current_period_end`). Defaults to `false`.
  bool? cancelAtPeriodEnd;

  ///  Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions and mark the subscription as `active`. Defaults to `charge_automatically`.
  SubscriptionsPostRequestBodyCollectionMethod? collectionMethod;

  ///  Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
  String? currency;

  ///  Number of days a customer has to pay invoices generated by this subscription. Valid only for subscriptions where `collection_method` is set to `send_invoice`.
  int? daysUntilDue;

  ///  ID of the default payment method for the subscription. It must belong to the customer associated with the subscription. This takes precedence over `default_source`. If neither are set, invoices will use the customer's [invoice_settings.default_payment_method](https://docs.stripe.com/api/customers/object#customer_object-invoice_settings-default_payment_method) or [default_source](https://docs.stripe.com/api/customers/object#customer_object-default_source).
  String? defaultPaymentMethod;

  ///  ID of the default payment source for the subscription. It must belong to the customer associated with the subscription and be in a chargeable state. If `default_payment_method` is also set, `default_payment_method` will take precedence. If neither are set, invoices will use the customer's [invoice_settings.default_payment_method](https://docs.stripe.com/api/customers/object#customer_object-invoice_settings-default_payment_method) or [default_source](https://docs.stripe.com/api/customers/object#customer_object-default_source).
  String? defaultSource;

  ///  The tax rates that will apply to any subscription item that does not have `tax_rates` set. Invoices created will have their `default_tax_rates` populated from the subscription.
  SubscriptionsPostRequestBodyDefaultTaxRates? defaultTaxRates;

  ///  The coupons to redeem into discounts for the subscription. If not specified or empty, inherits the discount from the subscription's customer.
  SubscriptionsPostRequestBodyDiscounts? discounts;

  ///  Specifies which fields in the response should be expanded.
  Iterable<String>? expand;

  ///  All invoices will be billed using the specified settings.
  SubscriptionsPostRequestBodyInvoiceSettings? invoiceSettings;

  ///  A list of up to 20 subscription items, each with an attached price.
  Iterable<SubscriptionsPostRequestBodyItems>? items;

  ///  Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
  String? metadata;

  ///  Indicates if a customer is on or off-session while an invoice payment is attempted. Defaults to `false` (on-session).
  bool? offSession;

  ///  Only applies to subscriptions with `collection_method=charge_automatically`.Use `allow_incomplete` to create Subscriptions with `status=incomplete` if the first invoice can't be paid. Creating Subscriptions with this status allows you to manage scenarios where additional customer actions are needed to pay a subscription's invoice. For example, SCA regulation may require 3DS authentication to complete payment. See the [SCA Migration Guide](https://docs.stripe.com/billing/migration/strong-customer-authentication) for Billing to learn more. This is the default behavior.Use `default_incomplete` to create Subscriptions with `status=incomplete` when the first invoice requires payment, otherwise start as active. Subscriptions transition to `status=active` when successfully confirming the PaymentIntent on the first invoice. This allows simpler management of scenarios where additional customer actions are needed to pay a subscription’s invoice, such as failed payments, [SCA regulation](https://docs.stripe.com/billing/migration/strong-customer-authentication), or collecting a mandate for a bank debit payment method. If the PaymentIntent is not confirmed within 23 hours Subscriptions transition to `status=incomplete_expired`, which is a terminal state.Use `error_if_incomplete` if you want Stripe to return an HTTP 402 status code if a subscription's first invoice can't be paid. For example, if a payment method requires 3DS authentication due to SCA regulation and further customer action is needed, this parameter doesn't create a Subscription and returns an error instead. This was the default behavior for API versions prior to 2019-03-14. See the [changelog](https://docs.stripe.com/upgrades#2019-03-14) to learn more.`pending_if_incomplete` is only used with updates and cannot be passed when creating a Subscription.Subscriptions with `collection_method=send_invoice` are automatically activated regardless of the first Invoice status.
  SubscriptionsPostRequestBodyPaymentBehavior? paymentBehavior;

  ///  Payment settings to pass to invoices created by the subscription.
  SubscriptionsPostRequestBodyPaymentSettings? paymentSettings;

  ///  Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling [Create an invoice](https://docs.stripe.com/api#create_invoice) for the given subscription at the specified interval.
  SubscriptionsPostRequestBodyPendingInvoiceItemInterval?
      pendingInvoiceItemInterval;

  ///  Determines how to handle [prorations](https://docs.stripe.com/billing/subscriptions/prorations) resulting from the `billing_cycle_anchor`. If no value is passed, the default is `create_prorations`.
  SubscriptionsPostRequestBodyProrationBehavior? prorationBehavior;

  ///  If specified, the funds from the subscription's invoices will be transferred to the destination and the ID of the resulting transfers will be found on the resulting charges.
  SubscriptionsPostRequestBodyTransferData? transferData;

  ///  Unix timestamp representing the end of the trial period the customer will get before being charged for the first time. If set, trial_end will override the default trial period of the plan the customer is being subscribed to. The special value `now` can be provided to end the customer's trial immediately. Can be at most two years from `billing_cycle_anchor`. See [Using trial periods on subscriptions](https://docs.stripe.com/billing/subscriptions/trials) to learn more.
  SubscriptionsPostRequestBodyTrialEnd? trialEnd;

  ///  Indicates if a plan's `trial_period_days` should be applied to the subscription. Setting `trial_end` per subscription is preferred, and this defaults to `false`. Setting this flag to `true` together with `trial_end` is not allowed. See [Using trial periods on subscriptions](https://docs.stripe.com/billing/subscriptions/trials) to learn more.
  bool? trialFromPlan;

  ///  Integer representing the number of trial period days before the customer is charged for the first time. This will always overwrite any trials that might apply via a subscribed plan. See [Using trial periods on subscriptions](https://docs.stripe.com/billing/subscriptions/trials) to learn more.
  int? trialPeriodDays;

  ///  Settings related to subscription trials.
  SubscriptionsPostRequestBodyTrialSettings? trialSettings;

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static SubscriptionsPostRequestBody createFromDiscriminatorValue(
      ParseNode parseNode) {
    return SubscriptionsPostRequestBody();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['add_invoice_items'] = (node) => addInvoiceItems =
        node.getCollectionOfObjectValues<
                SubscriptionsPostRequestBodyAddInvoiceItems>(
            SubscriptionsPostRequestBodyAddInvoiceItems
                .createFromDiscriminatorValue);
    deserializerMap['application_fee_percent'] = (node) =>
        applicationFeePercent = node
            .getObjectValue<SubscriptionsPostRequestBodyApplicationFeePercent>(
                SubscriptionsPostRequestBodyApplicationFeePercent
                    .createFromDiscriminatorValue);
    deserializerMap['automatic_tax'] = (node) => automaticTax =
        node.getObjectValue<SubscriptionsPostRequestBodyAutomaticTax>(
            SubscriptionsPostRequestBodyAutomaticTax
                .createFromDiscriminatorValue);
    deserializerMap['backdate_start_date'] =
        (node) => backdateStartDate = node.getIntValue();
    deserializerMap['billing_cycle_anchor'] =
        (node) => billingCycleAnchor = node.getIntValue();
    deserializerMap['billing_thresholds'] = (node) => billingThresholds =
        node.getObjectValue<SubscriptionsPostRequestBodyBillingThresholds>(
            SubscriptionsPostRequestBodyBillingThresholds
                .createFromDiscriminatorValue);
    deserializerMap['cancel_at'] = (node) => cancelAt =
        node.getObjectValue<SubscriptionsPostRequestBodyCancelAt>(
            SubscriptionsPostRequestBodyCancelAt.createFromDiscriminatorValue);
    deserializerMap['cancel_at_period_end'] =
        (node) => cancelAtPeriodEnd = node.getBoolValue();
    deserializerMap['collection_method'] = (node) => collectionMethod =
        node.getEnumValue<SubscriptionsPostRequestBodyCollectionMethod>(
            (stringValue) => SubscriptionsPostRequestBodyCollectionMethod.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['currency'] = (node) => currency = node.getStringValue();
    deserializerMap['days_until_due'] =
        (node) => daysUntilDue = node.getIntValue();
    deserializerMap['default_payment_method'] =
        (node) => defaultPaymentMethod = node.getStringValue();
    deserializerMap['default_source'] =
        (node) => defaultSource = node.getStringValue();
    deserializerMap['default_tax_rates'] = (node) => defaultTaxRates =
        node.getObjectValue<SubscriptionsPostRequestBodyDefaultTaxRates>(
            SubscriptionsPostRequestBodyDefaultTaxRates
                .createFromDiscriminatorValue);
    deserializerMap['discounts'] = (node) => discounts =
        node.getObjectValue<SubscriptionsPostRequestBodyDiscounts>(
            SubscriptionsPostRequestBodyDiscounts.createFromDiscriminatorValue);
    deserializerMap['expand'] =
        (node) => expand = node.getCollectionOfPrimitiveValues<String>();
    deserializerMap['invoice_settings'] = (node) => invoiceSettings =
        node.getObjectValue<SubscriptionsPostRequestBodyInvoiceSettings>(
            SubscriptionsPostRequestBodyInvoiceSettings
                .createFromDiscriminatorValue);
    deserializerMap['items'] = (node) => items =
        node.getCollectionOfObjectValues<SubscriptionsPostRequestBodyItems>(
            SubscriptionsPostRequestBodyItems.createFromDiscriminatorValue);
    deserializerMap['metadata'] = (node) => metadata = node.getStringValue();
    deserializerMap['off_session'] = (node) => offSession = node.getBoolValue();
    deserializerMap['payment_behavior'] = (node) => paymentBehavior =
        node.getEnumValue<SubscriptionsPostRequestBodyPaymentBehavior>(
            (stringValue) => SubscriptionsPostRequestBodyPaymentBehavior.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['payment_settings'] = (node) => paymentSettings =
        node.getObjectValue<SubscriptionsPostRequestBodyPaymentSettings>(
            SubscriptionsPostRequestBodyPaymentSettings
                .createFromDiscriminatorValue);
    deserializerMap['pending_invoice_item_interval'] = (node) =>
        pendingInvoiceItemInterval = node.getObjectValue<
                SubscriptionsPostRequestBodyPendingInvoiceItemInterval>(
            SubscriptionsPostRequestBodyPendingInvoiceItemInterval
                .createFromDiscriminatorValue);
    deserializerMap['proration_behavior'] = (node) => prorationBehavior =
        node.getEnumValue<SubscriptionsPostRequestBodyProrationBehavior>(
            (stringValue) => SubscriptionsPostRequestBodyProrationBehavior
                .values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['transfer_data'] = (node) => transferData =
        node.getObjectValue<SubscriptionsPostRequestBodyTransferData>(
            SubscriptionsPostRequestBodyTransferData
                .createFromDiscriminatorValue);
    deserializerMap['trial_end'] = (node) => trialEnd =
        node.getObjectValue<SubscriptionsPostRequestBodyTrialEnd>(
            SubscriptionsPostRequestBodyTrialEnd.createFromDiscriminatorValue);
    deserializerMap['trial_from_plan'] =
        (node) => trialFromPlan = node.getBoolValue();
    deserializerMap['trial_period_days'] =
        (node) => trialPeriodDays = node.getIntValue();
    deserializerMap['trial_settings'] = (node) => trialSettings =
        node.getObjectValue<SubscriptionsPostRequestBodyTrialSettings>(
            SubscriptionsPostRequestBodyTrialSettings
                .createFromDiscriminatorValue);
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeCollectionOfObjectValues<
            SubscriptionsPostRequestBodyAddInvoiceItems>(
        'add_invoice_items', addInvoiceItems);
    writer.writeObjectValue<SubscriptionsPostRequestBodyApplicationFeePercent>(
        'application_fee_percent', applicationFeePercent);
    writer.writeObjectValue<SubscriptionsPostRequestBodyAutomaticTax>(
        'automatic_tax', automaticTax);
    writer.writeIntValue('backdate_start_date', backdateStartDate);
    writer.writeIntValue('billing_cycle_anchor', billingCycleAnchor);
    writer.writeObjectValue<SubscriptionsPostRequestBodyBillingThresholds>(
        'billing_thresholds', billingThresholds);
    writer.writeObjectValue<SubscriptionsPostRequestBodyCancelAt>(
        'cancel_at', cancelAt);
    writer.writeBoolValue('cancel_at_period_end', value: cancelAtPeriodEnd);
    writer.writeEnumValue<SubscriptionsPostRequestBodyCollectionMethod>(
        'collection_method', collectionMethod, (e) => e?.value);
    writer.writeStringValue('currency', currency);
    writer.writeIntValue('days_until_due', daysUntilDue);
    writer.writeStringValue('default_payment_method', defaultPaymentMethod);
    writer.writeStringValue('default_source', defaultSource);
    writer.writeObjectValue<SubscriptionsPostRequestBodyDefaultTaxRates>(
        'default_tax_rates', defaultTaxRates);
    writer.writeObjectValue<SubscriptionsPostRequestBodyDiscounts>(
        'discounts', discounts);
    writer.writeCollectionOfPrimitiveValues<String?>('expand', expand);
    writer.writeObjectValue<SubscriptionsPostRequestBodyInvoiceSettings>(
        'invoice_settings', invoiceSettings);
    writer.writeCollectionOfObjectValues<SubscriptionsPostRequestBodyItems>(
        'items', items);
    writer.writeStringValue('metadata', metadata);
    writer.writeBoolValue('off_session', value: offSession);
    writer.writeEnumValue<SubscriptionsPostRequestBodyPaymentBehavior>(
        'payment_behavior', paymentBehavior, (e) => e?.value);
    writer.writeObjectValue<SubscriptionsPostRequestBodyPaymentSettings>(
        'payment_settings', paymentSettings);
    writer.writeObjectValue<
            SubscriptionsPostRequestBodyPendingInvoiceItemInterval>(
        'pending_invoice_item_interval', pendingInvoiceItemInterval);
    writer.writeEnumValue<SubscriptionsPostRequestBodyProrationBehavior>(
        'proration_behavior', prorationBehavior, (e) => e?.value);
    writer.writeObjectValue<SubscriptionsPostRequestBodyTransferData>(
        'transfer_data', transferData);
    writer.writeObjectValue<SubscriptionsPostRequestBodyTrialEnd>(
        'trial_end', trialEnd);
    writer.writeBoolValue('trial_from_plan', value: trialFromPlan);
    writer.writeIntValue('trial_period_days', trialPeriodDays);
    writer.writeObjectValue<SubscriptionsPostRequestBodyTrialSettings>(
        'trial_settings', trialSettings);
  }
}
