// ignore_for_file: type=lint
/// auto generated
///  The code for the type of error.
enum AccountRequirementsErrorCode {
  externalRequest('external_request'),
  informationMissing('information_missing'),
  invalidAddressCityStatePostalCode('invalid_address_city_state_postal_code'),
  invalidAddressHighwayContractBox('invalid_address_highway_contract_box'),
  invalidAddressPrivateMailbox('invalid_address_private_mailbox'),
  invalidBusinessProfileName('invalid_business_profile_name'),
  invalidBusinessProfileNameDenylisted(
      'invalid_business_profile_name_denylisted'),
  invalidCompanyNameDenylisted('invalid_company_name_denylisted'),
  invalidDobAgeOverMaximum('invalid_dob_age_over_maximum'),
  invalidDobAgeUnder18('invalid_dob_age_under_18'),
  invalidDobAgeUnderMinimum('invalid_dob_age_under_minimum'),
  invalidProductDescriptionLength('invalid_product_description_length'),
  invalidProductDescriptionUrlMatch('invalid_product_description_url_match'),
  invalidRepresentativeCountry('invalid_representative_country'),
  invalidSignator('invalid_signator'),
  invalidStatementDescriptorBusinessMismatch(
      'invalid_statement_descriptor_business_mismatch'),
  invalidStatementDescriptorDenylisted(
      'invalid_statement_descriptor_denylisted'),
  invalidStatementDescriptorLength('invalid_statement_descriptor_length'),
  invalidStatementDescriptorPrefixDenylisted(
      'invalid_statement_descriptor_prefix_denylisted'),
  invalidStatementDescriptorPrefixMismatch(
      'invalid_statement_descriptor_prefix_mismatch'),
  invalidStreetAddress('invalid_street_address'),
  invalidTaxId('invalid_tax_id'),
  invalidTaxIdFormat('invalid_tax_id_format'),
  invalidTosAcceptance('invalid_tos_acceptance'),
  invalidUrlDenylisted('invalid_url_denylisted'),
  invalidUrlFormat('invalid_url_format'),
  invalidUrlWebPresenceDetected('invalid_url_web_presence_detected'),
  invalidUrlWebsiteBusinessInformationMismatch(
      'invalid_url_website_business_information_mismatch'),
  invalidUrlWebsiteEmpty('invalid_url_website_empty'),
  invalidUrlWebsiteInaccessible('invalid_url_website_inaccessible'),
  invalidUrlWebsiteInaccessibleGeoblocked(
      'invalid_url_website_inaccessible_geoblocked'),
  invalidUrlWebsiteInaccessiblePasswordProtected(
      'invalid_url_website_inaccessible_password_protected'),
  invalidUrlWebsiteIncomplete('invalid_url_website_incomplete'),
  invalidUrlWebsiteIncompleteCancellationPolicy(
      'invalid_url_website_incomplete_cancellation_policy'),
  invalidUrlWebsiteIncompleteCustomerServiceDetails(
      'invalid_url_website_incomplete_customer_service_details'),
  invalidUrlWebsiteIncompleteLegalRestrictions(
      'invalid_url_website_incomplete_legal_restrictions'),
  invalidUrlWebsiteIncompleteRefundPolicy(
      'invalid_url_website_incomplete_refund_policy'),
  invalidUrlWebsiteIncompleteReturnPolicy(
      'invalid_url_website_incomplete_return_policy'),
  invalidUrlWebsiteIncompleteTermsAndConditions(
      'invalid_url_website_incomplete_terms_and_conditions'),
  invalidUrlWebsiteIncompleteUnderConstruction(
      'invalid_url_website_incomplete_under_construction'),
  invalidUrlWebsiteOther('invalid_url_website_other'),
  invalidValueOther('invalid_value_other'),
  unsupportedBusinessType('unsupported_business_type'),
  verificationDirectorsMismatch('verification_directors_mismatch'),
  verificationDocumentAddressMismatch('verification_document_address_mismatch'),
  verificationDocumentAddressMissing('verification_document_address_missing'),
  verificationDocumentCorrupt('verification_document_corrupt'),
  verificationDocumentCountryNotSupported(
      'verification_document_country_not_supported'),
  verificationDocumentDirectorsMismatch(
      'verification_document_directors_mismatch'),
  verificationDocumentDobMismatch('verification_document_dob_mismatch'),
  verificationDocumentDuplicateType('verification_document_duplicate_type'),
  verificationDocumentExpired('verification_document_expired'),
  verificationDocumentFailedCopy('verification_document_failed_copy'),
  verificationDocumentFailedGreyscale('verification_document_failed_greyscale'),
  verificationDocumentFailedOther('verification_document_failed_other'),
  verificationDocumentFailedTestMode('verification_document_failed_test_mode'),
  verificationDocumentFraudulent('verification_document_fraudulent'),
  verificationDocumentIdNumberMismatch(
      'verification_document_id_number_mismatch'),
  verificationDocumentIdNumberMissing(
      'verification_document_id_number_missing'),
  verificationDocumentIncomplete('verification_document_incomplete'),
  verificationDocumentInvalid('verification_document_invalid'),
  verificationDocumentIssueOrExpiryDateMissing(
      'verification_document_issue_or_expiry_date_missing'),
  verificationDocumentManipulated('verification_document_manipulated'),
  verificationDocumentMissingBack('verification_document_missing_back'),
  verificationDocumentMissingFront('verification_document_missing_front'),
  verificationDocumentNameMismatch('verification_document_name_mismatch'),
  verificationDocumentNameMissing('verification_document_name_missing'),
  verificationDocumentNationalityMismatch(
      'verification_document_nationality_mismatch'),
  verificationDocumentNotReadable('verification_document_not_readable'),
  verificationDocumentNotSigned('verification_document_not_signed'),
  verificationDocumentNotUploaded('verification_document_not_uploaded'),
  verificationDocumentPhotoMismatch('verification_document_photo_mismatch'),
  verificationDocumentTooLarge('verification_document_too_large'),
  verificationDocumentTypeNotSupported(
      'verification_document_type_not_supported'),
  verificationExtraneousDirectors('verification_extraneous_directors'),
  verificationFailedAddressMatch('verification_failed_address_match'),
  verificationFailedAuthorizerAuthority(
      'verification_failed_authorizer_authority'),
  verificationFailedBusinessIecNumber(
      'verification_failed_business_iec_number'),
  verificationFailedDocumentMatch('verification_failed_document_match'),
  verificationFailedIdNumberMatch('verification_failed_id_number_match'),
  verificationFailedKeyedIdentity('verification_failed_keyed_identity'),
  verificationFailedKeyedMatch('verification_failed_keyed_match'),
  verificationFailedNameMatch('verification_failed_name_match'),
  verificationFailedOther('verification_failed_other'),
  verificationFailedRepresentativeAuthority(
      'verification_failed_representative_authority'),
  verificationFailedResidentialAddress(
      'verification_failed_residential_address'),
  verificationFailedTaxIdMatch('verification_failed_tax_id_match'),
  verificationFailedTaxIdNotIssued('verification_failed_tax_id_not_issued'),
  verificationLegalEntityStructureMismatch(
      'verification_legal_entity_structure_mismatch'),
  verificationMissingDirectors('verification_missing_directors'),
  verificationMissingExecutives('verification_missing_executives'),
  verificationMissingOwners('verification_missing_owners'),
  verificationRejectedOwnershipExemptionReason(
      'verification_rejected_ownership_exemption_reason'),
  verificationRequiresAdditionalMemorandumOfAssociations(
      'verification_requires_additional_memorandum_of_associations'),
  verificationRequiresAdditionalProofOfRegistration(
      'verification_requires_additional_proof_of_registration'),
  verificationSupportability('verification_supportability');

  const AccountRequirementsErrorCode(this.value);
  final String value;
}
