// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './connect_account_reference.dart';

/// auto generated
class InvoiceSettingSubscriptionSchedulePhaseSetting
    implements AdditionalDataHolder, Parsable {
  ///  The account tax IDs associated with this phase of the subscription schedule. Will be set on invoices generated by this phase of the subscription schedule.
  Iterable<String>? accountTaxIds;

  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
  int? daysUntilDue;

  ///  The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
  ConnectAccountReference? issuer;

  /// Instantiates a new [InvoiceSettingSubscriptionSchedulePhaseSetting] and sets the default values.
  InvoiceSettingSubscriptionSchedulePhaseSetting() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static InvoiceSettingSubscriptionSchedulePhaseSetting
      createFromDiscriminatorValue(ParseNode parseNode) {
    return InvoiceSettingSubscriptionSchedulePhaseSetting();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['account_tax_ids'] =
        (node) => accountTaxIds = node.getCollectionOfPrimitiveValues<String>();
    deserializerMap['days_until_due'] =
        (node) => daysUntilDue = node.getIntValue();
    deserializerMap['issuer'] = (node) => issuer =
        node.getObjectValue<ConnectAccountReference>(
            ConnectAccountReference.createFromDiscriminatorValue);
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeCollectionOfPrimitiveValues<String?>(
        'account_tax_ids', accountTaxIds);
    writer.writeIntValue('days_until_due', daysUntilDue);
    writer.writeObjectValue<ConnectAccountReference>('issuer', issuer);
    writer.writeAdditionalData(additionalData);
  }
}
