// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './connect_account_reference.dart';

/// auto generated
class InvoiceSettingQuoteSetting implements AdditionalDataHolder, Parsable {
  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  Number of days within which a customer must pay invoices generated by this quote. This value will be `null` for quotes where `collection_method=charge_automatically`.
  int? daysUntilDue;

  ///  The issuer property
  ConnectAccountReference? issuer;

  /// Instantiates a new [InvoiceSettingQuoteSetting] and sets the default values.
  InvoiceSettingQuoteSetting() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static InvoiceSettingQuoteSetting createFromDiscriminatorValue(
      ParseNode parseNode) {
    return InvoiceSettingQuoteSetting();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['days_until_due'] =
        (node) => daysUntilDue = node.getIntValue();
    deserializerMap['issuer'] = (node) => issuer =
        node.getObjectValue<ConnectAccountReference>(
            ConnectAccountReference.createFromDiscriminatorValue);
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeIntValue('days_until_due', daysUntilDue);
    writer.writeObjectValue<ConnectAccountReference>('issuer', issuer);
    writer.writeAdditionalData(additionalData);
  }
}
