// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './paypal_seller_protection.dart';

/// auto generated
class PaymentMethodDetailsPaypal implements AdditionalDataHolder, Parsable {
  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  Two-letter ISO code representing the buyer's country. Values are provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? country;

  ///  Owner's email. Values are provided by PayPal directly(if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? payerEmail;

  ///  PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
  String? payerId;

  ///  Owner's full name. Values provided by PayPal directly(if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? payerName;

  ///  The level of protection offered as defined by PayPal Seller Protection for Merchants, for this transaction.
  PaypalSellerProtection? sellerProtection;

  ///  A unique ID generated by PayPal for this transaction.
  String? transactionId;

  /// Instantiates a new [PaymentMethodDetailsPaypal] and sets the default values.
  PaymentMethodDetailsPaypal() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static PaymentMethodDetailsPaypal createFromDiscriminatorValue(
      ParseNode parseNode) {
    return PaymentMethodDetailsPaypal();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['country'] = (node) => country = node.getStringValue();
    deserializerMap['payer_email'] =
        (node) => payerEmail = node.getStringValue();
    deserializerMap['payer_id'] = (node) => payerId = node.getStringValue();
    deserializerMap['payer_name'] = (node) => payerName = node.getStringValue();
    deserializerMap['seller_protection'] = (node) => sellerProtection =
        node.getObjectValue<PaypalSellerProtection>(
            PaypalSellerProtection.createFromDiscriminatorValue);
    deserializerMap['transaction_id'] =
        (node) => transactionId = node.getStringValue();
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeStringValue('country', country);
    writer.writeStringValue('payer_email', payerEmail);
    writer.writeStringValue('payer_id', payerId);
    writer.writeStringValue('payer_name', payerName);
    writer.writeObjectValue<PaypalSellerProtection>(
        'seller_protection', sellerProtection);
    writer.writeStringValue('transaction_id', transactionId);
    writer.writeAdditionalData(additionalData);
  }
}
