// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './api_errors.dart';
import './payment_flows_automatic_payment_methods_payment_intent.dart';
import './payment_flows_payment_details.dart';
import './payment_flows_payment_intent_async_workflows.dart';
import './payment_flows_payment_intent_presentment_details.dart';
import './payment_intent_amount_details.dart';
import './payment_intent_application.dart';
import './payment_intent_cancellation_reason.dart';
import './payment_intent_capture_method.dart';
import './payment_intent_confirmation_method.dart';
import './payment_intent_customer.dart';
import './payment_intent_excluded_payment_method_types.dart';
import './payment_intent_latest_charge.dart';
import './payment_intent_metadata.dart';
import './payment_intent_next_action.dart';
import './payment_intent_object.dart';
import './payment_intent_on_behalf_of.dart';
import './payment_intent_payment_method.dart';
import './payment_intent_payment_method_options.dart';
import './payment_intent_processing.dart';
import './payment_intent_review.dart';
import './payment_intent_setup_future_usage.dart';
import './payment_intent_status.dart';
import './payment_method_config_biz_payment_method_configuration_details.dart';
import './shipping.dart';
import './transfer_data.dart';

/// auto generated
/// A PaymentIntent guides you through the process of collecting a payment from your customer.We recommend that you create exactly one PaymentIntent for each order orcustomer session in your system. You can reference the PaymentIntent later tosee the history of payment attempts for a particular session.A PaymentIntent transitions through[multiple statuses](/payments/paymentintents/lifecycle)throughout its lifetime as it interfaces with Stripe.js to performauthentication flows and ultimately creates at most one successful charge.Related guide: [Payment Intents API](https://docs.stripe.com/payments/payment-intents)
class PaymentIntent implements AdditionalDataHolder, Parsable {
  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  Amount intended to be collected by this PaymentIntent. A positive integer representing how much to charge in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal) (e.g., 100 cents to charge $1.00 or 100 to charge ¥100, a zero-decimal currency). The minimum amount is $0.50 US or [equivalent in charge currency](https://docs.stripe.com/currencies#minimum-and-maximum-charge-amounts). The amount value supports up to eight digits (e.g., a value of 99999999 for a USD charge of $999,999.99).
  int? amount;

  ///  Amount that can be captured from this PaymentIntent.
  int? amountCapturable;

  ///  The amount_details property
  PaymentIntentAmountDetails? amountDetails;

  ///  Amount that this PaymentIntent collects.
  int? amountReceived;

  ///  ID of the Connect application that created the PaymentIntent.
  PaymentIntentApplication? application;

  ///  The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account. The amount of the application fee collected will be capped at the total amount captured. For more information, see the PaymentIntents [use case for connected accounts](https://docs.stripe.com/payments/connected-accounts).
  int? applicationFeeAmount;

  ///  Settings to configure compatible payment methods from the [Stripe Dashboard](https://dashboard.stripe.com/settings/payment_methods)
  PaymentFlowsAutomaticPaymentMethodsPaymentIntent? automaticPaymentMethods;

  ///  Populated when `status` is `canceled`, this is the time at which the PaymentIntent was canceled. Measured in seconds since the Unix epoch.
  int? canceledAt;

  ///  Reason for cancellation of this PaymentIntent, either user-provided (`duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`) or generated by Stripe internally (`failed_invoice`, `void_invoice`, `automatic`, or `expired`).
  PaymentIntentCancellationReason? cancellationReason;

  ///  Controls when the funds will be captured from the customer's account.
  PaymentIntentCaptureMethod? captureMethod;

  ///  The client secret of this PaymentIntent. Used for client-side retrieval using a publishable key. The client secret can be used to complete a payment from your frontend. It should not be stored, logged, or exposed to anyone other than the customer. Make sure that you have TLS enabled on any page that includes the client secret.Refer to our docs to [accept a payment](https://docs.stripe.com/payments/accept-a-payment?ui=elements) and learn about how `client_secret` should be handled.
  String? clientSecret;

  ///  Describes whether we can confirm this PaymentIntent automatically, or if it requires customer action to confirm the payment.
  PaymentIntentConfirmationMethod? confirmationMethod;

  ///  Time at which the object was created. Measured in seconds since the Unix epoch.
  int? created;

  ///  Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
  String? currency;

  ///  ID of the Customer this PaymentIntent belongs to, if one exists.Payment methods attached to other Customers cannot be used with this PaymentIntent.If [setup_future_usage](https://api.stripe.com#payment_intent_object-setup_future_usage) is set and this PaymentIntent's payment method is not `card_present`, then the payment method attaches to the Customer after the PaymentIntent has been confirmed and any required actions from the user are complete. If the payment method is `card_present` and isn't a digital wallet, then a [generated_card](https://docs.stripe.com/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card is created and attached to the Customer instead.
  PaymentIntentCustomer? customer;

  ///  ID of the Account representing the customer that this PaymentIntent belongs to, if one exists.Payment methods attached to other Accounts cannot be used with this PaymentIntent.If [setup_future_usage](https://api.stripe.com#payment_intent_object-setup_future_usage) is set and this PaymentIntent's payment method is not `card_present`, then the payment method attaches to the Account after the PaymentIntent has been confirmed and any required actions from the user are complete. If the payment method is `card_present` and isn't a digital wallet, then a [generated_card](https://docs.stripe.com/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card is created and attached to the Account instead.
  String? customerAccount;

  ///  An arbitrary string attached to the object. Often useful for displaying to users.
  String? description;

  ///  The list of payment method types to exclude from use with this payment.
  Iterable<PaymentIntentExcludedPaymentMethodTypes>? excludedPaymentMethodTypes;

  ///  The hooks property
  PaymentFlowsPaymentIntentAsyncWorkflows? hooks;

  ///  Unique identifier for the object.
  String? id;

  ///  The payment error encountered in the previous PaymentIntent confirmation. It will be cleared if the PaymentIntent is later updated for any reason.
  ApiErrors? lastPaymentError;

  ///  ID of the latest [Charge object](https://docs.stripe.com/api/charges) created by this PaymentIntent. This property is `null` until PaymentIntent confirmation is attempted.
  PaymentIntentLatestCharge? latestCharge;

  ///  Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
  bool? livemode;

  ///  Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Learn more about [storing information in metadata](https://docs.stripe.com/payments/payment-intents/creating-payment-intents#storing-information-in-metadata).
  PaymentIntentMetadata? metadata;

  ///  If present, this property tells you what actions you need to take in order for your customer to fulfill a payment using the provided source.
  PaymentIntentNextAction? nextAction;

  ///  String representing the object's type. Objects of the same type share the same value.
  PaymentIntentObject? object;

  ///  You can specify the settlement merchant as theconnected account using the `on_behalf_of` attribute on the charge. See the PaymentIntents [use case for connected accounts](/payments/connected-accounts) for details.
  PaymentIntentOnBehalfOf? onBehalfOf;

  ///  The payment_details property
  PaymentFlowsPaymentDetails? paymentDetails;

  ///  ID of the payment method used in this PaymentIntent.
  PaymentIntentPaymentMethod? paymentMethod;

  ///  Information about the [payment method configuration](https://docs.stripe.com/api/payment_method_configurations) used for this PaymentIntent.
  PaymentMethodConfigBizPaymentMethodConfigurationDetails?
      paymentMethodConfigurationDetails;

  ///  Payment-method-specific configuration for this PaymentIntent.
  PaymentIntentPaymentMethodOptions? paymentMethodOptions;

  ///  The list of payment method types (e.g. card) that this PaymentIntent is allowed to use. A comprehensive list of valid payment method types can be found [here](https://docs.stripe.com/api/payment_methods/object#payment_method_object-type).
  Iterable<String>? paymentMethodTypes;

  ///  The presentment_details property
  PaymentFlowsPaymentIntentPresentmentDetails? presentmentDetails;

  ///  If present, this property tells you about the processing state of the payment.
  PaymentIntentProcessing? processing;

  ///  Email address that the receipt for the resulting payment will be sent to. If `receipt_email` is specified for a payment in live mode, a receipt will be sent regardless of your [email settings](https://dashboard.stripe.com/account/emails).
  String? receiptEmail;

  ///  ID of the review associated with this PaymentIntent, if any.
  PaymentIntentReview? review;

  ///  Indicates that you intend to make future payments with this PaymentIntent's payment method.If you provide a Customer with the PaymentIntent, you can use this parameter to [attach the payment method](/payments/save-during-payment) to the Customer after the PaymentIntent is confirmed and the customer completes any required actions. If you don't provide a Customer, you can still [attach](/api/payment_methods/attach) the payment method to a Customer after the transaction completes.If the payment method is `card_present` and isn't a digital wallet, Stripe creates and attaches a [generated_card](/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card to the Customer instead.When processing card payments, Stripe uses `setup_future_usage` to help you comply with regional legislation and network rules, such as [SCA](/strong-customer-authentication).
  PaymentIntentSetupFutureUsage? setupFutureUsage;

  ///  Shipping information for this PaymentIntent.
  Shipping? shipping;

  ///  Text that appears on the customer's statement as the statement descriptor for a non-card charge. This value overrides the account's default statement descriptor. For information about requirements, including the 22-character limit, see [the Statement Descriptor docs](https://docs.stripe.com/get-started/account/statement-descriptors).Setting this value for a card charge returns an error. For card charges, set the [statement_descriptor_suffix](https://docs.stripe.com/get-started/account/statement-descriptors#dynamic) instead.
  String? statementDescriptor;

  ///  Provides information about a card charge. Concatenated to the account's [statement descriptor prefix](https://docs.stripe.com/get-started/account/statement-descriptors#static) to form the complete statement descriptor that appears on the customer's statement.
  String? statementDescriptorSuffix;

  ///  Status of this PaymentIntent, one of `requires_payment_method`, `requires_confirmation`, `requires_action`, `processing`, `requires_capture`, `canceled`, or `succeeded`. Read more about each PaymentIntent [status](https://docs.stripe.com/payments/intents#intent-statuses).
  PaymentIntentStatus? status;

  ///  The data that automatically creates a Transfer after the payment finalizes. Learn more about the [use case for connected accounts](https://docs.stripe.com/payments/connected-accounts).
  TransferData? transferData;

  ///  A string that identifies the resulting payment as part of a group. Learn more about the [use case for connected accounts](https://docs.stripe.com/connect/separate-charges-and-transfers).
  String? transferGroup;

  /// Instantiates a new [PaymentIntent] and sets the default values.
  PaymentIntent() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static PaymentIntent createFromDiscriminatorValue(ParseNode parseNode) {
    return PaymentIntent();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['amount'] = (node) => amount = node.getIntValue();
    deserializerMap['amount_capturable'] =
        (node) => amountCapturable = node.getIntValue();
    deserializerMap['amount_details'] = (node) => amountDetails =
        node.getObjectValue<PaymentIntentAmountDetails>(
            PaymentIntentAmountDetails.createFromDiscriminatorValue);
    deserializerMap['amount_received'] =
        (node) => amountReceived = node.getIntValue();
    deserializerMap['application'] = (node) => application =
        node.getObjectValue<PaymentIntentApplication>(
            PaymentIntentApplication.createFromDiscriminatorValue);
    deserializerMap['application_fee_amount'] =
        (node) => applicationFeeAmount = node.getIntValue();
    deserializerMap['automatic_payment_methods'] = (node) =>
        automaticPaymentMethods = node
            .getObjectValue<PaymentFlowsAutomaticPaymentMethodsPaymentIntent>(
                PaymentFlowsAutomaticPaymentMethodsPaymentIntent
                    .createFromDiscriminatorValue);
    deserializerMap['canceled_at'] = (node) => canceledAt = node.getIntValue();
    deserializerMap['cancellation_reason'] = (node) => cancellationReason =
        node.getEnumValue<PaymentIntentCancellationReason>((stringValue) =>
            PaymentIntentCancellationReason.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['capture_method'] = (node) => captureMethod =
        node.getEnumValue<PaymentIntentCaptureMethod>((stringValue) =>
            PaymentIntentCaptureMethod.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['client_secret'] =
        (node) => clientSecret = node.getStringValue();
    deserializerMap['confirmation_method'] = (node) => confirmationMethod =
        node.getEnumValue<PaymentIntentConfirmationMethod>((stringValue) =>
            PaymentIntentConfirmationMethod.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['created'] = (node) => created = node.getIntValue();
    deserializerMap['currency'] = (node) => currency = node.getStringValue();
    deserializerMap['customer'] = (node) => customer =
        node.getObjectValue<PaymentIntentCustomer>(
            PaymentIntentCustomer.createFromDiscriminatorValue);
    deserializerMap['customer_account'] =
        (node) => customerAccount = node.getStringValue();
    deserializerMap['description'] =
        (node) => description = node.getStringValue();
    deserializerMap['excluded_payment_method_types'] = (node) =>
        excludedPaymentMethodTypes = node
            .getCollectionOfEnumValues<PaymentIntentExcludedPaymentMethodTypes>(
                (stringValue) => PaymentIntentExcludedPaymentMethodTypes.values
                    .where((enumVal) => enumVal.value == stringValue)
                    .firstOrNull);
    deserializerMap['hooks'] = (node) => hooks = node.getObjectValue<
            PaymentFlowsPaymentIntentAsyncWorkflows>(
        PaymentFlowsPaymentIntentAsyncWorkflows.createFromDiscriminatorValue);
    deserializerMap['id'] = (node) => id = node.getStringValue();
    deserializerMap['last_payment_error'] = (node) => lastPaymentError =
        node.getObjectValue<ApiErrors>(ApiErrors.createFromDiscriminatorValue);
    deserializerMap['latest_charge'] = (node) => latestCharge =
        node.getObjectValue<PaymentIntentLatestCharge>(
            PaymentIntentLatestCharge.createFromDiscriminatorValue);
    deserializerMap['livemode'] = (node) => livemode = node.getBoolValue();
    deserializerMap['metadata'] = (node) => metadata =
        node.getObjectValue<PaymentIntentMetadata>(
            PaymentIntentMetadata.createFromDiscriminatorValue);
    deserializerMap['next_action'] = (node) => nextAction =
        node.getObjectValue<PaymentIntentNextAction>(
            PaymentIntentNextAction.createFromDiscriminatorValue);
    deserializerMap['object'] = (node) => object =
        node.getEnumValue<PaymentIntentObject>((stringValue) =>
            PaymentIntentObject.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['on_behalf_of'] = (node) => onBehalfOf =
        node.getObjectValue<PaymentIntentOnBehalfOf>(
            PaymentIntentOnBehalfOf.createFromDiscriminatorValue);
    deserializerMap['payment_details'] = (node) => paymentDetails =
        node.getObjectValue<PaymentFlowsPaymentDetails>(
            PaymentFlowsPaymentDetails.createFromDiscriminatorValue);
    deserializerMap['payment_method'] = (node) => paymentMethod =
        node.getObjectValue<PaymentIntentPaymentMethod>(
            PaymentIntentPaymentMethod.createFromDiscriminatorValue);
    deserializerMap['payment_method_configuration_details'] = (node) =>
        paymentMethodConfigurationDetails = node.getObjectValue<
                PaymentMethodConfigBizPaymentMethodConfigurationDetails>(
            PaymentMethodConfigBizPaymentMethodConfigurationDetails
                .createFromDiscriminatorValue);
    deserializerMap['payment_method_options'] = (node) => paymentMethodOptions =
        node.getObjectValue<PaymentIntentPaymentMethodOptions>(
            PaymentIntentPaymentMethodOptions.createFromDiscriminatorValue);
    deserializerMap['payment_method_types'] = (node) =>
        paymentMethodTypes = node.getCollectionOfPrimitiveValues<String>();
    deserializerMap['presentment_details'] = (node) => presentmentDetails =
        node.getObjectValue<PaymentFlowsPaymentIntentPresentmentDetails>(
            PaymentFlowsPaymentIntentPresentmentDetails
                .createFromDiscriminatorValue);
    deserializerMap['processing'] = (node) => processing =
        node.getObjectValue<PaymentIntentProcessing>(
            PaymentIntentProcessing.createFromDiscriminatorValue);
    deserializerMap['receipt_email'] =
        (node) => receiptEmail = node.getStringValue();
    deserializerMap['review'] = (node) => review =
        node.getObjectValue<PaymentIntentReview>(
            PaymentIntentReview.createFromDiscriminatorValue);
    deserializerMap['setup_future_usage'] = (node) => setupFutureUsage =
        node.getEnumValue<PaymentIntentSetupFutureUsage>((stringValue) =>
            PaymentIntentSetupFutureUsage.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['shipping'] = (node) => shipping =
        node.getObjectValue<Shipping>(Shipping.createFromDiscriminatorValue);
    deserializerMap['statement_descriptor'] =
        (node) => statementDescriptor = node.getStringValue();
    deserializerMap['statement_descriptor_suffix'] =
        (node) => statementDescriptorSuffix = node.getStringValue();
    deserializerMap['status'] = (node) => status =
        node.getEnumValue<PaymentIntentStatus>((stringValue) =>
            PaymentIntentStatus.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['transfer_data'] = (node) => transferData =
        node.getObjectValue<TransferData>(
            TransferData.createFromDiscriminatorValue);
    deserializerMap['transfer_group'] =
        (node) => transferGroup = node.getStringValue();
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeIntValue('amount', amount);
    writer.writeIntValue('amount_capturable', amountCapturable);
    writer.writeObjectValue<PaymentIntentAmountDetails>(
        'amount_details', amountDetails);
    writer.writeIntValue('amount_received', amountReceived);
    writer.writeObjectValue<PaymentIntentApplication>(
        'application', application);
    writer.writeIntValue('application_fee_amount', applicationFeeAmount);
    writer.writeObjectValue<PaymentFlowsAutomaticPaymentMethodsPaymentIntent>(
        'automatic_payment_methods', automaticPaymentMethods);
    writer.writeIntValue('canceled_at', canceledAt);
    writer.writeEnumValue<PaymentIntentCancellationReason>(
        'cancellation_reason', cancellationReason, (e) => e?.value);
    writer.writeEnumValue<PaymentIntentCaptureMethod>(
        'capture_method', captureMethod, (e) => e?.value);
    writer.writeStringValue('client_secret', clientSecret);
    writer.writeEnumValue<PaymentIntentConfirmationMethod>(
        'confirmation_method', confirmationMethod, (e) => e?.value);
    writer.writeIntValue('created', created);
    writer.writeStringValue('currency', currency);
    writer.writeObjectValue<PaymentIntentCustomer>('customer', customer);
    writer.writeStringValue('customer_account', customerAccount);
    writer.writeStringValue('description', description);
    writer.writeCollectionOfEnumValues<PaymentIntentExcludedPaymentMethodTypes>(
        'excluded_payment_method_types',
        excludedPaymentMethodTypes,
        (e) => e?.value);
    writer.writeObjectValue<PaymentFlowsPaymentIntentAsyncWorkflows>(
        'hooks', hooks);
    writer.writeStringValue('id', id);
    writer.writeObjectValue<ApiErrors>('last_payment_error', lastPaymentError);
    writer.writeObjectValue<PaymentIntentLatestCharge>(
        'latest_charge', latestCharge);
    writer.writeBoolValue('livemode', value: livemode);
    writer.writeObjectValue<PaymentIntentMetadata>('metadata', metadata);
    writer.writeObjectValue<PaymentIntentNextAction>('next_action', nextAction);
    writer.writeEnumValue<PaymentIntentObject>(
        'object', object, (e) => e?.value);
    writer.writeObjectValue<PaymentIntentOnBehalfOf>(
        'on_behalf_of', onBehalfOf);
    writer.writeObjectValue<PaymentFlowsPaymentDetails>(
        'payment_details', paymentDetails);
    writer.writeObjectValue<PaymentIntentPaymentMethod>(
        'payment_method', paymentMethod);
    writer.writeObjectValue<
            PaymentMethodConfigBizPaymentMethodConfigurationDetails>(
        'payment_method_configuration_details',
        paymentMethodConfigurationDetails);
    writer.writeObjectValue<PaymentIntentPaymentMethodOptions>(
        'payment_method_options', paymentMethodOptions);
    writer.writeCollectionOfPrimitiveValues<String?>(
        'payment_method_types', paymentMethodTypes);
    writer.writeObjectValue<PaymentFlowsPaymentIntentPresentmentDetails>(
        'presentment_details', presentmentDetails);
    writer.writeObjectValue<PaymentIntentProcessing>('processing', processing);
    writer.writeStringValue('receipt_email', receiptEmail);
    writer.writeObjectValue<PaymentIntentReview>('review', review);
    writer.writeEnumValue<PaymentIntentSetupFutureUsage>(
        'setup_future_usage', setupFutureUsage, (e) => e?.value);
    writer.writeObjectValue<Shipping>('shipping', shipping);
    writer.writeStringValue('statement_descriptor', statementDescriptor);
    writer.writeStringValue(
        'statement_descriptor_suffix', statementDescriptorSuffix);
    writer.writeEnumValue<PaymentIntentStatus>(
        'status', status, (e) => e?.value);
    writer.writeObjectValue<TransferData>('transfer_data', transferData);
    writer.writeStringValue('transfer_group', transferGroup);
    writer.writeAdditionalData(additionalData);
  }
}
