// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './payment_method_details_ideal_bank.dart';
import './payment_method_details_ideal_bic.dart';
import './payment_method_details_ideal_generated_sepa_debit.dart';
import './payment_method_details_ideal_generated_sepa_debit_mandate.dart';

/// auto generated
class PaymentMethodDetailsIdeal implements AdditionalDataHolder, Parsable {
  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `buut`, `finom`, `handelsbanken`, `ing`, `knab`, `mollie`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
  PaymentMethodDetailsIdealBank? bank;

  ///  The Bank Identifier Code of the customer's bank.
  PaymentMethodDetailsIdealBic? bic;

  ///  The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
  PaymentMethodDetailsIdealGeneratedSepaDebit? generatedSepaDebit;

  ///  The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
  PaymentMethodDetailsIdealGeneratedSepaDebitMandate? generatedSepaDebitMandate;

  ///  Last four characters of the IBAN.
  String? ibanLast4;

  ///  Unique transaction ID generated by iDEAL.
  String? transactionId;

  ///  Owner's verified full name. Values are verified or provided by iDEAL directly(if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? verifiedName;

  /// Instantiates a new [PaymentMethodDetailsIdeal] and sets the default values.
  PaymentMethodDetailsIdeal() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static PaymentMethodDetailsIdeal createFromDiscriminatorValue(
      ParseNode parseNode) {
    return PaymentMethodDetailsIdeal();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['bank'] = (node) => bank =
        node.getEnumValue<PaymentMethodDetailsIdealBank>((stringValue) =>
            PaymentMethodDetailsIdealBank.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['bic'] = (node) => bic =
        node.getEnumValue<PaymentMethodDetailsIdealBic>((stringValue) =>
            PaymentMethodDetailsIdealBic.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['generated_sepa_debit'] = (node) => generatedSepaDebit =
        node.getObjectValue<PaymentMethodDetailsIdealGeneratedSepaDebit>(
            PaymentMethodDetailsIdealGeneratedSepaDebit
                .createFromDiscriminatorValue);
    deserializerMap['generated_sepa_debit_mandate'] = (node) =>
        generatedSepaDebitMandate = node
            .getObjectValue<PaymentMethodDetailsIdealGeneratedSepaDebitMandate>(
                PaymentMethodDetailsIdealGeneratedSepaDebitMandate
                    .createFromDiscriminatorValue);
    deserializerMap['iban_last4'] = (node) => ibanLast4 = node.getStringValue();
    deserializerMap['transaction_id'] =
        (node) => transactionId = node.getStringValue();
    deserializerMap['verified_name'] =
        (node) => verifiedName = node.getStringValue();
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeEnumValue<PaymentMethodDetailsIdealBank>(
        'bank', bank, (e) => e?.value);
    writer.writeEnumValue<PaymentMethodDetailsIdealBic>(
        'bic', bic, (e) => e?.value);
    writer.writeObjectValue<PaymentMethodDetailsIdealGeneratedSepaDebit>(
        'generated_sepa_debit', generatedSepaDebit);
    writer.writeObjectValue<PaymentMethodDetailsIdealGeneratedSepaDebitMandate>(
        'generated_sepa_debit_mandate', generatedSepaDebitMandate);
    writer.writeStringValue('iban_last4', ibanLast4);
    writer.writeStringValue('transaction_id', transactionId);
    writer.writeStringValue('verified_name', verifiedName);
    writer.writeAdditionalData(additionalData);
  }
}
