// ignore_for_file: type=lint
/// auto generated
///  Reason for cancellation of this PaymentIntent, either user-provided (`duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`) or generated by Stripe internally (`failed_invoice`, `void_invoice`, `automatic`, or `expired`).
enum PaymentIntentCancellationReason {
  abandoned('abandoned'),
  automatic('automatic'),
  duplicate('duplicate'),
  expired('expired'),
  failedInvoice('failed_invoice'),
  fraudulent('fraudulent'),
  requestedByCustomer('requested_by_customer'),
  voidInvoice('void_invoice');

  const PaymentIntentCancellationReason(this.value);
  final String value;
}
