// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './payment_method_details_sofort_generated_sepa_debit.dart';
import './payment_method_details_sofort_generated_sepa_debit_mandate.dart';
import './payment_method_details_sofort_preferred_language.dart';

/// auto generated
class PaymentMethodDetailsSofort implements AdditionalDataHolder, Parsable {
  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  Bank code of bank associated with the bank account.
  String? bankCode;

  ///  Name of the bank associated with the bank account.
  String? bankName;

  ///  Bank Identifier Code of the bank associated with the bank account.
  String? bic;

  ///  Two-letter ISO code representing the country the bank account is located in.
  String? country;

  ///  The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
  PaymentMethodDetailsSofortGeneratedSepaDebit? generatedSepaDebit;

  ///  The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
  PaymentMethodDetailsSofortGeneratedSepaDebitMandate?
      generatedSepaDebitMandate;

  ///  Last four characters of the IBAN.
  String? ibanLast4;

  ///  Preferred language of the SOFORT authorization page that the customer is redirected to.Can be one of `de`, `en`, `es`, `fr`, `it`, `nl`, or `pl`
  PaymentMethodDetailsSofortPreferredLanguage? preferredLanguage;

  ///  Owner's verified full name. Values are verified or provided by SOFORT directly(if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? verifiedName;

  /// Instantiates a new [PaymentMethodDetailsSofort] and sets the default values.
  PaymentMethodDetailsSofort() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static PaymentMethodDetailsSofort createFromDiscriminatorValue(
      ParseNode parseNode) {
    return PaymentMethodDetailsSofort();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['bank_code'] = (node) => bankCode = node.getStringValue();
    deserializerMap['bank_name'] = (node) => bankName = node.getStringValue();
    deserializerMap['bic'] = (node) => bic = node.getStringValue();
    deserializerMap['country'] = (node) => country = node.getStringValue();
    deserializerMap['generated_sepa_debit'] = (node) => generatedSepaDebit =
        node.getObjectValue<PaymentMethodDetailsSofortGeneratedSepaDebit>(
            PaymentMethodDetailsSofortGeneratedSepaDebit
                .createFromDiscriminatorValue);
    deserializerMap['generated_sepa_debit_mandate'] = (node) =>
        generatedSepaDebitMandate = node.getObjectValue<
                PaymentMethodDetailsSofortGeneratedSepaDebitMandate>(
            PaymentMethodDetailsSofortGeneratedSepaDebitMandate
                .createFromDiscriminatorValue);
    deserializerMap['iban_last4'] = (node) => ibanLast4 = node.getStringValue();
    deserializerMap['preferred_language'] = (node) => preferredLanguage =
        node.getEnumValue<PaymentMethodDetailsSofortPreferredLanguage>(
            (stringValue) => PaymentMethodDetailsSofortPreferredLanguage.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['verified_name'] =
        (node) => verifiedName = node.getStringValue();
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeStringValue('bank_code', bankCode);
    writer.writeStringValue('bank_name', bankName);
    writer.writeStringValue('bic', bic);
    writer.writeStringValue('country', country);
    writer.writeObjectValue<PaymentMethodDetailsSofortGeneratedSepaDebit>(
        'generated_sepa_debit', generatedSepaDebit);
    writer
        .writeObjectValue<PaymentMethodDetailsSofortGeneratedSepaDebitMandate>(
            'generated_sepa_debit_mandate', generatedSepaDebitMandate);
    writer.writeStringValue('iban_last4', ibanLast4);
    writer.writeEnumValue<PaymentMethodDetailsSofortPreferredLanguage>(
        'preferred_language', preferredLanguage, (e) => e?.value);
    writer.writeStringValue('verified_name', verifiedName);
    writer.writeAdditionalData(additionalData);
  }
}
