// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './payment_flows_payment_intent_presentment_details.dart';
import './refund_balance_transaction.dart';
import './refund_charge.dart';
import './refund_destination_details.dart';
import './refund_failure_balance_transaction.dart';
import './refund_metadata.dart';
import './refund_next_action.dart';
import './refund_object.dart';
import './refund_payment_intent.dart';
import './refund_pending_reason.dart';
import './refund_reason.dart';
import './refund_source_transfer_reversal.dart';
import './refund_transfer_reversal.dart';

/// auto generated
/// Refund objects allow you to refund a previously created charge that isn'trefunded yet. Funds are refunded to the credit or debit card that'sinitially charged.Related guide: [Refunds](https://docs.stripe.com/refunds)
class Refund implements AdditionalDataHolder, Parsable {
  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  Amount, in cents (or local equivalent).
  int? amount;

  ///  Balance transaction that describes the impact on your account balance.
  RefundBalanceTransaction? balanceTransaction;

  ///  ID of the charge that's refunded.
  RefundCharge? charge;

  ///  Time at which the object was created. Measured in seconds since the Unix epoch.
  int? created;

  ///  Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
  String? currency;

  ///  An arbitrary string attached to the object. You can use this for displaying to users (available on non-card refunds only).
  String? description;

  ///  The destination_details property
  RefundDestinationDetails? destinationDetails;

  ///  After the refund fails, this balance transaction describes the adjustment made on your account balance that reverses the initial balance transaction.
  RefundFailureBalanceTransaction? failureBalanceTransaction;

  ///  Provides the reason for the refund failure. Possible values are: `lost_or_stolen_card`, `expired_or_canceled_card`, `charge_for_pending_refund_disputed`, `insufficient_funds`, `declined`, `merchant_request`, or `unknown`.
  String? failureReason;

  ///  Unique identifier for the object.
  String? id;

  ///  For payment methods without native refund support (for example, Konbini, PromptPay), provide an email address for the customer to receive refund instructions.
  String? instructionsEmail;

  ///  Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
  RefundMetadata? metadata;

  ///  The next_action property
  RefundNextAction? nextAction;

  ///  String representing the object's type. Objects of the same type share the same value.
  RefundObject? object;

  ///  ID of the PaymentIntent that's refunded.
  RefundPaymentIntent? paymentIntent;

  ///  Provides the reason for why the refund is pending. Possible values are: `processing`, `insufficient_funds`, or `charge_pending`.
  RefundPendingReason? pendingReason;

  ///  The presentment_details property
  PaymentFlowsPaymentIntentPresentmentDetails? presentmentDetails;

  ///  Reason for the refund, which is either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).
  RefundReason? reason;

  ///  This is the transaction number that appears on email receipts sent for this refund.
  String? receiptNumber;

  ///  The transfer reversal that's associated with the refund. Only present if the charge came from another Stripe account.
  RefundSourceTransferReversal? sourceTransferReversal;

  ///  Status of the refund. This can be `pending`, `requires_action`, `succeeded`, `failed`, or `canceled`. Learn more about [failed refunds](https://docs.stripe.com/refunds#failed-refunds).
  String? status;

  ///  This refers to the transfer reversal object if the accompanying transfer reverses. This is only applicable if the charge was created using the destination parameter.
  RefundTransferReversal? transferReversal;

  /// Instantiates a new [Refund] and sets the default values.
  Refund() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static Refund createFromDiscriminatorValue(ParseNode parseNode) {
    return Refund();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['amount'] = (node) => amount = node.getIntValue();
    deserializerMap['balance_transaction'] = (node) => balanceTransaction =
        node.getObjectValue<RefundBalanceTransaction>(
            RefundBalanceTransaction.createFromDiscriminatorValue);
    deserializerMap['charge'] = (node) => charge =
        node.getObjectValue<RefundCharge>(
            RefundCharge.createFromDiscriminatorValue);
    deserializerMap['created'] = (node) => created = node.getIntValue();
    deserializerMap['currency'] = (node) => currency = node.getStringValue();
    deserializerMap['description'] =
        (node) => description = node.getStringValue();
    deserializerMap['destination_details'] = (node) => destinationDetails =
        node.getObjectValue<RefundDestinationDetails>(
            RefundDestinationDetails.createFromDiscriminatorValue);
    deserializerMap['failure_balance_transaction'] = (node) =>
        failureBalanceTransaction =
            node.getObjectValue<RefundFailureBalanceTransaction>(
                RefundFailureBalanceTransaction.createFromDiscriminatorValue);
    deserializerMap['failure_reason'] =
        (node) => failureReason = node.getStringValue();
    deserializerMap['id'] = (node) => id = node.getStringValue();
    deserializerMap['instructions_email'] =
        (node) => instructionsEmail = node.getStringValue();
    deserializerMap['metadata'] = (node) => metadata =
        node.getObjectValue<RefundMetadata>(
            RefundMetadata.createFromDiscriminatorValue);
    deserializerMap['next_action'] = (node) => nextAction =
        node.getObjectValue<RefundNextAction>(
            RefundNextAction.createFromDiscriminatorValue);
    deserializerMap['object'] = (node) => object =
        node.getEnumValue<RefundObject>((stringValue) => RefundObject.values
            .where((enumVal) => enumVal.value == stringValue)
            .firstOrNull);
    deserializerMap['payment_intent'] = (node) => paymentIntent =
        node.getObjectValue<RefundPaymentIntent>(
            RefundPaymentIntent.createFromDiscriminatorValue);
    deserializerMap['pending_reason'] = (node) => pendingReason =
        node.getEnumValue<RefundPendingReason>((stringValue) =>
            RefundPendingReason.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['presentment_details'] = (node) => presentmentDetails =
        node.getObjectValue<PaymentFlowsPaymentIntentPresentmentDetails>(
            PaymentFlowsPaymentIntentPresentmentDetails
                .createFromDiscriminatorValue);
    deserializerMap['reason'] = (node) => reason =
        node.getEnumValue<RefundReason>((stringValue) => RefundReason.values
            .where((enumVal) => enumVal.value == stringValue)
            .firstOrNull);
    deserializerMap['receipt_number'] =
        (node) => receiptNumber = node.getStringValue();
    deserializerMap['source_transfer_reversal'] = (node) =>
        sourceTransferReversal =
            node.getObjectValue<RefundSourceTransferReversal>(
                RefundSourceTransferReversal.createFromDiscriminatorValue);
    deserializerMap['status'] = (node) => status = node.getStringValue();
    deserializerMap['transfer_reversal'] = (node) => transferReversal =
        node.getObjectValue<RefundTransferReversal>(
            RefundTransferReversal.createFromDiscriminatorValue);
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeIntValue('amount', amount);
    writer.writeObjectValue<RefundBalanceTransaction>(
        'balance_transaction', balanceTransaction);
    writer.writeObjectValue<RefundCharge>('charge', charge);
    writer.writeIntValue('created', created);
    writer.writeStringValue('currency', currency);
    writer.writeStringValue('description', description);
    writer.writeObjectValue<RefundDestinationDetails>(
        'destination_details', destinationDetails);
    writer.writeObjectValue<RefundFailureBalanceTransaction>(
        'failure_balance_transaction', failureBalanceTransaction);
    writer.writeStringValue('failure_reason', failureReason);
    writer.writeStringValue('id', id);
    writer.writeStringValue('instructions_email', instructionsEmail);
    writer.writeObjectValue<RefundMetadata>('metadata', metadata);
    writer.writeObjectValue<RefundNextAction>('next_action', nextAction);
    writer.writeEnumValue<RefundObject>('object', object, (e) => e?.value);
    writer.writeObjectValue<RefundPaymentIntent>(
        'payment_intent', paymentIntent);
    writer.writeEnumValue<RefundPendingReason>(
        'pending_reason', pendingReason, (e) => e?.value);
    writer.writeObjectValue<PaymentFlowsPaymentIntentPresentmentDetails>(
        'presentment_details', presentmentDetails);
    writer.writeEnumValue<RefundReason>('reason', reason, (e) => e?.value);
    writer.writeStringValue('receipt_number', receiptNumber);
    writer.writeObjectValue<RefundSourceTransferReversal>(
        'source_transfer_reversal', sourceTransferReversal);
    writer.writeStringValue('status', status);
    writer.writeObjectValue<RefundTransferReversal>(
        'transfer_reversal', transferReversal);
    writer.writeAdditionalData(additionalData);
  }
}
