// ignore_for_file: type=lint
/// auto generated
///  Reason for the refund, which is either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).
enum RefundReason {
  duplicate('duplicate'),
  expiredUncapturedCharge('expired_uncaptured_charge'),
  fraudulent('fraudulent'),
  requestedByCustomer('requested_by_customer');

  const RefundReason(this.value);
  final String value;
}
