// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './payment_method_details_card_present_offline.dart';
import './setup_attempt_payment_method_details_card_present_generated_card.dart';

/// auto generated
class SetupAttemptPaymentMethodDetailsCardPresent
    implements AdditionalDataHolder, Parsable {
  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  The ID of the Card PaymentMethod which was generated by this SetupAttempt.
  SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard? generatedCard;

  ///  Details about payments collected offline.
  PaymentMethodDetailsCardPresentOffline? offline;

  /// Instantiates a new [SetupAttemptPaymentMethodDetailsCardPresent] and sets the default values.
  SetupAttemptPaymentMethodDetailsCardPresent() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static SetupAttemptPaymentMethodDetailsCardPresent
      createFromDiscriminatorValue(ParseNode parseNode) {
    return SetupAttemptPaymentMethodDetailsCardPresent();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['generated_card'] = (node) => generatedCard =
        node.getObjectValue<
                SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard>(
            SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard
                .createFromDiscriminatorValue);
    deserializerMap['offline'] = (node) => offline = node.getObjectValue<
            PaymentMethodDetailsCardPresentOffline>(
        PaymentMethodDetailsCardPresentOffline.createFromDiscriminatorValue);
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeObjectValue<
            SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard>(
        'generated_card', generatedCard);
    writer.writeObjectValue<PaymentMethodDetailsCardPresentOffline>(
        'offline', offline);
    writer.writeAdditionalData(additionalData);
  }
}
