// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './setup_attempt_payment_method_details_ideal_bank.dart';
import './setup_attempt_payment_method_details_ideal_bic.dart';
import './setup_attempt_payment_method_details_ideal_generated_sepa_debit.dart';
import './setup_attempt_payment_method_details_ideal_generated_sepa_debit_mandate.dart';

/// auto generated
class SetupAttemptPaymentMethodDetailsIdeal
    implements AdditionalDataHolder, Parsable {
  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `buut`, `finom`, `handelsbanken`, `ing`, `knab`, `mollie`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
  SetupAttemptPaymentMethodDetailsIdealBank? bank;

  ///  The Bank Identifier Code of the customer's bank.
  SetupAttemptPaymentMethodDetailsIdealBic? bic;

  ///  The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
  SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit? generatedSepaDebit;

  ///  The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
  SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate?
      generatedSepaDebitMandate;

  ///  Last four characters of the IBAN.
  String? ibanLast4;

  ///  Owner's verified full name. Values are verified or provided by iDEAL directly(if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? verifiedName;

  /// Instantiates a new [SetupAttemptPaymentMethodDetailsIdeal] and sets the default values.
  SetupAttemptPaymentMethodDetailsIdeal() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static SetupAttemptPaymentMethodDetailsIdeal createFromDiscriminatorValue(
      ParseNode parseNode) {
    return SetupAttemptPaymentMethodDetailsIdeal();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['bank'] = (node) => bank =
        node.getEnumValue<SetupAttemptPaymentMethodDetailsIdealBank>(
            (stringValue) => SetupAttemptPaymentMethodDetailsIdealBank.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['bic'] = (node) => bic =
        node.getEnumValue<SetupAttemptPaymentMethodDetailsIdealBic>(
            (stringValue) => SetupAttemptPaymentMethodDetailsIdealBic.values
                .where((enumVal) => enumVal.value == stringValue)
                .firstOrNull);
    deserializerMap['generated_sepa_debit'] = (node) => generatedSepaDebit =
        node.getObjectValue<
                SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit>(
            SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit
                .createFromDiscriminatorValue);
    deserializerMap['generated_sepa_debit_mandate'] = (node) =>
        generatedSepaDebitMandate = node.getObjectValue<
                SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate>(
            SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate
                .createFromDiscriminatorValue);
    deserializerMap['iban_last4'] = (node) => ibanLast4 = node.getStringValue();
    deserializerMap['verified_name'] =
        (node) => verifiedName = node.getStringValue();
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeEnumValue<SetupAttemptPaymentMethodDetailsIdealBank>(
        'bank', bank, (e) => e?.value);
    writer.writeEnumValue<SetupAttemptPaymentMethodDetailsIdealBic>(
        'bic', bic, (e) => e?.value);
    writer.writeObjectValue<
            SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit>(
        'generated_sepa_debit', generatedSepaDebit);
    writer.writeObjectValue<
            SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate>(
        'generated_sepa_debit_mandate', generatedSepaDebitMandate);
    writer.writeStringValue('iban_last4', ibanLast4);
    writer.writeStringValue('verified_name', verifiedName);
    writer.writeAdditionalData(additionalData);
  }
}
