// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './connect_account_reference.dart';

/// auto generated
class SubscriptionsResourceSubscriptionInvoiceSettings
    implements AdditionalDataHolder, Parsable {
  ///  The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.
  Iterable<String>? accountTaxIds;

  ///  Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
  @override
  Map<String, Object?> additionalData;

  ///  The issuer property
  ConnectAccountReference? issuer;

  /// Instantiates a new [SubscriptionsResourceSubscriptionInvoiceSettings] and sets the default values.
  SubscriptionsResourceSubscriptionInvoiceSettings() : additionalData = {};

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static SubscriptionsResourceSubscriptionInvoiceSettings
      createFromDiscriminatorValue(ParseNode parseNode) {
    return SubscriptionsResourceSubscriptionInvoiceSettings();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['account_tax_ids'] =
        (node) => accountTaxIds = node.getCollectionOfPrimitiveValues<String>();
    deserializerMap['issuer'] = (node) => issuer =
        node.getObjectValue<ConnectAccountReference>(
            ConnectAccountReference.createFromDiscriminatorValue);
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeCollectionOfPrimitiveValues<String?>(
        'account_tax_ids', accountTaxIds);
    writer.writeObjectValue<ConnectAccountReference>('issuer', issuer);
    writer.writeAdditionalData(additionalData);
  }
}
