// ignore_for_file: type=lint
/// auto generated
enum ConfirmPostRequestBodyPaymentMethodDataType {
  acssDebit('acss_debit'),
  affirm('affirm'),
  afterpayClearpay('afterpay_clearpay'),
  alipay('alipay'),
  alma('alma'),
  amazonPay('amazon_pay'),
  auBecsDebit('au_becs_debit'),
  bacsDebit('bacs_debit'),
  bancontact('bancontact'),
  billie('billie'),
  blik('blik'),
  boleto('boleto'),
  cashapp('cashapp'),
  crypto('crypto'),
  customerBalance('customer_balance'),
  eps('eps'),
  fpx('fpx'),
  giropay('giropay'),
  grabpay('grabpay'),
  ideal('ideal'),
  kakaoPay('kakao_pay'),
  klarna('klarna'),
  konbini('konbini'),
  krCard('kr_card'),
  link('link'),
  mbWay('mb_way'),
  mobilepay('mobilepay'),
  multibanco('multibanco'),
  naverPay('naver_pay'),
  nzBankAccount('nz_bank_account'),
  oxxo('oxxo'),
  p24('p24'),
  payByBank('pay_by_bank'),
  payco('payco'),
  paynow('paynow'),
  paypal('paypal'),
  payto('payto'),
  pix('pix'),
  promptpay('promptpay'),
  revolutPay('revolut_pay'),
  samsungPay('samsung_pay'),
  satispay('satispay'),
  sepaDebit('sepa_debit'),
  sofort('sofort'),
  swish('swish'),
  twint('twint'),
  usBankAccount('us_bank_account'),
  wechatPay('wechat_pay'),
  zip('zip');

  const ConfirmPostRequestBodyPaymentMethodDataType(this.value);
  final String value;
}
