// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './with_subscription_exposed_post_request_body_add_invoice_items.dart';
import './with_subscription_exposed_post_request_body_application_fee_percent.dart';
import './with_subscription_exposed_post_request_body_automatic_tax.dart';
import './with_subscription_exposed_post_request_body_billing_cycle_anchor.dart';
import './with_subscription_exposed_post_request_body_billing_thresholds.dart';
import './with_subscription_exposed_post_request_body_cancel_at.dart';
import './with_subscription_exposed_post_request_body_cancellation_details.dart';
import './with_subscription_exposed_post_request_body_collection_method.dart';
import './with_subscription_exposed_post_request_body_default_source.dart';
import './with_subscription_exposed_post_request_body_default_tax_rates.dart';
import './with_subscription_exposed_post_request_body_discounts.dart';
import './with_subscription_exposed_post_request_body_invoice_settings.dart';
import './with_subscription_exposed_post_request_body_items.dart';
import './with_subscription_exposed_post_request_body_pause_collection.dart';
import './with_subscription_exposed_post_request_body_payment_behavior.dart';
import './with_subscription_exposed_post_request_body_payment_settings.dart';
import './with_subscription_exposed_post_request_body_pending_invoice_item_interval.dart';
import './with_subscription_exposed_post_request_body_proration_behavior.dart';
import './with_subscription_exposed_post_request_body_transfer_data.dart';
import './with_subscription_exposed_post_request_body_trial_end.dart';
import './with_subscription_exposed_post_request_body_trial_settings.dart';

/// auto generated
class WithSubscriptionExposedPostRequestBody implements Parsable {
  ///  A list of prices and quantities that will generate invoice items appended to the next invoice for this subscription. You may pass up to 20 items.
  Iterable<WithSubscriptionExposedPostRequestBodyAddInvoiceItems>?
      addInvoiceItems;

  ///  A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice total that will be transferred to the application owner's Stripe account. The request must be made by a platform account on a connected account in order to set an application fee percentage. For more information, see the application fees [documentation](https://stripe.com/docs/connect/subscriptions#collecting-fees-on-subscriptions).
  WithSubscriptionExposedPostRequestBodyApplicationFeePercent?
      applicationFeePercent;

  ///  Automatic tax settings for this subscription. We recommend you only include this parameter when the existing value is being changed.
  WithSubscriptionExposedPostRequestBodyAutomaticTax? automaticTax;

  ///  Either `now` or `unchanged`. Setting the value to `now` resets the subscription's billing cycle anchor to the current time. For more information, see the billing cycle [documentation](https://docs.stripe.com/billing/subscriptions/billing-cycle).
  WithSubscriptionExposedPostRequestBodyBillingCycleAnchor? billingCycleAnchor;

  ///  Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period. When updating, pass an empty string to remove previously-defined thresholds.
  WithSubscriptionExposedPostRequestBodyBillingThresholds? billingThresholds;

  ///  A timestamp at which the subscription should cancel. If set to a date before the current period ends, this will cause a proration if prorations have been enabled using `proration_behavior`. If set during a future period, this will always cause a proration for that period.
  WithSubscriptionExposedPostRequestBodyCancelAt? cancelAt;

  ///  Indicate whether this subscription should cancel at the end of the current period (`current_period_end`). Defaults to `false`.
  bool? cancelAtPeriodEnd;

  ///  Details about why this subscription was cancelled
  WithSubscriptionExposedPostRequestBodyCancellationDetails?
      cancellationDetails;

  ///  Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions and mark the subscription as `active`. Defaults to `charge_automatically`.
  WithSubscriptionExposedPostRequestBodyCollectionMethod? collectionMethod;

  ///  Number of days a customer has to pay invoices generated by this subscription. Valid only for subscriptions where `collection_method` is set to `send_invoice`.
  int? daysUntilDue;

  ///  ID of the default payment method for the subscription. It must belong to the customer associated with the subscription. This takes precedence over `default_source`. If neither are set, invoices will use the customer's [invoice_settings.default_payment_method](https://docs.stripe.com/api/customers/object#customer_object-invoice_settings-default_payment_method) or [default_source](https://docs.stripe.com/api/customers/object#customer_object-default_source).
  String? defaultPaymentMethod;

  ///  ID of the default payment source for the subscription. It must belong to the customer associated with the subscription and be in a chargeable state. If `default_payment_method` is also set, `default_payment_method` will take precedence. If neither are set, invoices will use the customer's [invoice_settings.default_payment_method](https://docs.stripe.com/api/customers/object#customer_object-invoice_settings-default_payment_method) or [default_source](https://docs.stripe.com/api/customers/object#customer_object-default_source).
  WithSubscriptionExposedPostRequestBodyDefaultSource? defaultSource;

  ///  The tax rates that will apply to any subscription item that does not have `tax_rates` set. Invoices created will have their `default_tax_rates` populated from the subscription. Pass an empty string to remove previously-defined tax rates.
  WithSubscriptionExposedPostRequestBodyDefaultTaxRates? defaultTaxRates;

  ///  The coupons to redeem into discounts for the subscription. If not specified or empty, inherits the discount from the subscription's customer.
  WithSubscriptionExposedPostRequestBodyDiscounts? discounts;

  ///  Specifies which fields in the response should be expanded.
  Iterable<String>? expand;

  ///  All invoices will be billed using the specified settings.
  WithSubscriptionExposedPostRequestBodyInvoiceSettings? invoiceSettings;

  ///  A list of up to 20 subscription items, each with an attached price.
  Iterable<WithSubscriptionExposedPostRequestBodyItems>? items;

  ///  Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
  String? metadata;

  ///  Indicates if a customer is on or off-session while an invoice payment is attempted. Defaults to `false` (on-session).
  bool? offSession;

  ///  If specified, payment collection for this subscription will be paused. Note that the subscription status will be unchanged and will not be updated to `paused`. Learn more about [pausing collection](https://docs.stripe.com/billing/subscriptions/pause-payment).
  WithSubscriptionExposedPostRequestBodyPauseCollection? pauseCollection;

  ///  Use `allow_incomplete` to transition the subscription to `status=past_due` if a payment is required but cannot be paid. This allows you to manage scenarios where additional user actions are needed to pay a subscription's invoice. For example, SCA regulation may require 3DS authentication to complete payment. See the [SCA Migration Guide](https://docs.stripe.com/billing/migration/strong-customer-authentication) for Billing to learn more. This is the default behavior.Use `default_incomplete` to transition the subscription to `status=past_due` when payment is required and await explicit confirmation of the invoice's payment intent. This allows simpler management of scenarios where additional user actions are needed to pay a subscription’s invoice. Such as failed payments, [SCA regulation](https://docs.stripe.com/billing/migration/strong-customer-authentication), or collecting a mandate for a bank debit payment method.Use `pending_if_incomplete` to update the subscription using [pending updates](https://docs.stripe.com/billing/subscriptions/pending-updates). When you use `pending_if_incomplete` you can only pass the parameters [supported by pending updates](https://docs.stripe.com/billing/pending-updates-reference#supported-attributes).Use `error_if_incomplete` if you want Stripe to return an HTTP 402 status code if a subscription's invoice cannot be paid. For example, if a payment method requires 3DS authentication due to SCA regulation and further user action is needed, this parameter does not update the subscription and returns an error instead. This was the default behavior for API versions prior to 2019-03-14. See the [changelog](https://docs.stripe.com/changelog/2019-03-14) to learn more.
  WithSubscriptionExposedPostRequestBodyPaymentBehavior? paymentBehavior;

  ///  Payment settings to pass to invoices created by the subscription.
  WithSubscriptionExposedPostRequestBodyPaymentSettings? paymentSettings;

  ///  Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling [Create an invoice](https://docs.stripe.com/api#create_invoice) for the given subscription at the specified interval.
  WithSubscriptionExposedPostRequestBodyPendingInvoiceItemInterval?
      pendingInvoiceItemInterval;

  ///  Determines how to handle [prorations](https://docs.stripe.com/billing/subscriptions/prorations) when the billing cycle changes (e.g., when switching plans, resetting `billing_cycle_anchor=now`, or starting a trial), or if an item's `quantity` changes. The default value is `create_prorations`.
  WithSubscriptionExposedPostRequestBodyProrationBehavior? prorationBehavior;

  ///  If set, prorations will be calculated as though the subscription was updated at the given time. This can be used to apply exactly the same prorations that were previewed with the [create preview](https://stripe.com/docs/api/invoices/create_preview) endpoint. `proration_date` can also be used to implement custom proration logic, such as prorating by day instead of by second, by providing the time that you wish to use for proration calculations.
  int? prorationDate;

  ///  If specified, the funds from the subscription's invoices will be transferred to the destination and the ID of the resulting transfers will be found on the resulting charges. This will be unset if you POST an empty value.
  WithSubscriptionExposedPostRequestBodyTransferData? transferData;

  ///  Unix timestamp representing the end of the trial period the customer will get before being charged for the first time. This will always overwrite any trials that might apply via a subscribed plan. If set, trial_end will override the default trial period of the plan the customer is being subscribed to. The special value `now` can be provided to end the customer's trial immediately. Can be at most two years from `billing_cycle_anchor`.
  WithSubscriptionExposedPostRequestBodyTrialEnd? trialEnd;

  ///  Indicates if a plan's `trial_period_days` should be applied to the subscription. Setting `trial_end` per subscription is preferred, and this defaults to `false`. Setting this flag to `true` together with `trial_end` is not allowed. See [Using trial periods on subscriptions](https://docs.stripe.com/billing/subscriptions/trials) to learn more.
  bool? trialFromPlan;

  ///  Settings related to subscription trials.
  WithSubscriptionExposedPostRequestBodyTrialSettings? trialSettings;

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static WithSubscriptionExposedPostRequestBody createFromDiscriminatorValue(
      ParseNode parseNode) {
    return WithSubscriptionExposedPostRequestBody();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['add_invoice_items'] = (node) => addInvoiceItems =
        node.getCollectionOfObjectValues<
                WithSubscriptionExposedPostRequestBodyAddInvoiceItems>(
            WithSubscriptionExposedPostRequestBodyAddInvoiceItems
                .createFromDiscriminatorValue);
    deserializerMap['application_fee_percent'] = (node) =>
        applicationFeePercent = node.getObjectValue<
                WithSubscriptionExposedPostRequestBodyApplicationFeePercent>(
            WithSubscriptionExposedPostRequestBodyApplicationFeePercent
                .createFromDiscriminatorValue);
    deserializerMap['automatic_tax'] = (node) => automaticTax =
        node.getObjectValue<WithSubscriptionExposedPostRequestBodyAutomaticTax>(
            WithSubscriptionExposedPostRequestBodyAutomaticTax
                .createFromDiscriminatorValue);
    deserializerMap['billing_cycle_anchor'] = (node) => billingCycleAnchor =
        node.getEnumValue<
                WithSubscriptionExposedPostRequestBodyBillingCycleAnchor>(
            (stringValue) =>
                WithSubscriptionExposedPostRequestBodyBillingCycleAnchor.values
                    .where((enumVal) => enumVal.value == stringValue)
                    .firstOrNull);
    deserializerMap['billing_thresholds'] = (node) => billingThresholds =
        node.getObjectValue<
                WithSubscriptionExposedPostRequestBodyBillingThresholds>(
            WithSubscriptionExposedPostRequestBodyBillingThresholds
                .createFromDiscriminatorValue);
    deserializerMap['cancel_at'] = (node) => cancelAt =
        node.getObjectValue<WithSubscriptionExposedPostRequestBodyCancelAt>(
            WithSubscriptionExposedPostRequestBodyCancelAt
                .createFromDiscriminatorValue);
    deserializerMap['cancel_at_period_end'] =
        (node) => cancelAtPeriodEnd = node.getBoolValue();
    deserializerMap['cancellation_details'] = (node) => cancellationDetails =
        node.getObjectValue<
                WithSubscriptionExposedPostRequestBodyCancellationDetails>(
            WithSubscriptionExposedPostRequestBodyCancellationDetails
                .createFromDiscriminatorValue);
    deserializerMap['collection_method'] = (node) => collectionMethod = node
        .getEnumValue<WithSubscriptionExposedPostRequestBodyCollectionMethod>(
            (stringValue) =>
                WithSubscriptionExposedPostRequestBodyCollectionMethod.values
                    .where((enumVal) => enumVal.value == stringValue)
                    .firstOrNull);
    deserializerMap['days_until_due'] =
        (node) => daysUntilDue = node.getIntValue();
    deserializerMap['default_payment_method'] =
        (node) => defaultPaymentMethod = node.getStringValue();
    deserializerMap['default_source'] = (node) => defaultSource = node
        .getObjectValue<WithSubscriptionExposedPostRequestBodyDefaultSource>(
            WithSubscriptionExposedPostRequestBodyDefaultSource
                .createFromDiscriminatorValue);
    deserializerMap['default_tax_rates'] = (node) => defaultTaxRates = node
        .getObjectValue<WithSubscriptionExposedPostRequestBodyDefaultTaxRates>(
            WithSubscriptionExposedPostRequestBodyDefaultTaxRates
                .createFromDiscriminatorValue);
    deserializerMap['discounts'] = (node) => discounts =
        node.getObjectValue<WithSubscriptionExposedPostRequestBodyDiscounts>(
            WithSubscriptionExposedPostRequestBodyDiscounts
                .createFromDiscriminatorValue);
    deserializerMap['expand'] =
        (node) => expand = node.getCollectionOfPrimitiveValues<String>();
    deserializerMap['invoice_settings'] = (node) => invoiceSettings = node
        .getObjectValue<WithSubscriptionExposedPostRequestBodyInvoiceSettings>(
            WithSubscriptionExposedPostRequestBodyInvoiceSettings
                .createFromDiscriminatorValue);
    deserializerMap['items'] = (node) => items =
        node.getCollectionOfObjectValues<
                WithSubscriptionExposedPostRequestBodyItems>(
            WithSubscriptionExposedPostRequestBodyItems
                .createFromDiscriminatorValue);
    deserializerMap['metadata'] = (node) => metadata = node.getStringValue();
    deserializerMap['off_session'] = (node) => offSession = node.getBoolValue();
    deserializerMap['pause_collection'] = (node) => pauseCollection = node
        .getObjectValue<WithSubscriptionExposedPostRequestBodyPauseCollection>(
            WithSubscriptionExposedPostRequestBodyPauseCollection
                .createFromDiscriminatorValue);
    deserializerMap['payment_behavior'] = (node) => paymentBehavior = node
        .getEnumValue<WithSubscriptionExposedPostRequestBodyPaymentBehavior>(
            (stringValue) =>
                WithSubscriptionExposedPostRequestBodyPaymentBehavior.values
                    .where((enumVal) => enumVal.value == stringValue)
                    .firstOrNull);
    deserializerMap['payment_settings'] = (node) => paymentSettings = node
        .getObjectValue<WithSubscriptionExposedPostRequestBodyPaymentSettings>(
            WithSubscriptionExposedPostRequestBodyPaymentSettings
                .createFromDiscriminatorValue);
    deserializerMap['pending_invoice_item_interval'] = (node) =>
        pendingInvoiceItemInterval = node.getObjectValue<
                WithSubscriptionExposedPostRequestBodyPendingInvoiceItemInterval>(
            WithSubscriptionExposedPostRequestBodyPendingInvoiceItemInterval
                .createFromDiscriminatorValue);
    deserializerMap['proration_behavior'] = (node) => prorationBehavior = node
        .getEnumValue<WithSubscriptionExposedPostRequestBodyProrationBehavior>(
            (stringValue) =>
                WithSubscriptionExposedPostRequestBodyProrationBehavior.values
                    .where((enumVal) => enumVal.value == stringValue)
                    .firstOrNull);
    deserializerMap['proration_date'] =
        (node) => prorationDate = node.getIntValue();
    deserializerMap['transfer_data'] = (node) => transferData =
        node.getObjectValue<WithSubscriptionExposedPostRequestBodyTransferData>(
            WithSubscriptionExposedPostRequestBodyTransferData
                .createFromDiscriminatorValue);
    deserializerMap['trial_end'] = (node) => trialEnd =
        node.getObjectValue<WithSubscriptionExposedPostRequestBodyTrialEnd>(
            WithSubscriptionExposedPostRequestBodyTrialEnd
                .createFromDiscriminatorValue);
    deserializerMap['trial_from_plan'] =
        (node) => trialFromPlan = node.getBoolValue();
    deserializerMap['trial_settings'] = (node) => trialSettings = node
        .getObjectValue<WithSubscriptionExposedPostRequestBodyTrialSettings>(
            WithSubscriptionExposedPostRequestBodyTrialSettings
                .createFromDiscriminatorValue);
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeCollectionOfObjectValues<
            WithSubscriptionExposedPostRequestBodyAddInvoiceItems>(
        'add_invoice_items', addInvoiceItems);
    writer.writeObjectValue<
            WithSubscriptionExposedPostRequestBodyApplicationFeePercent>(
        'application_fee_percent', applicationFeePercent);
    writer.writeObjectValue<WithSubscriptionExposedPostRequestBodyAutomaticTax>(
        'automatic_tax', automaticTax);
    writer.writeEnumValue<
            WithSubscriptionExposedPostRequestBodyBillingCycleAnchor>(
        'billing_cycle_anchor', billingCycleAnchor, (e) => e?.value);
    writer.writeObjectValue<
            WithSubscriptionExposedPostRequestBodyBillingThresholds>(
        'billing_thresholds', billingThresholds);
    writer.writeObjectValue<WithSubscriptionExposedPostRequestBodyCancelAt>(
        'cancel_at', cancelAt);
    writer.writeBoolValue('cancel_at_period_end', value: cancelAtPeriodEnd);
    writer.writeObjectValue<
            WithSubscriptionExposedPostRequestBodyCancellationDetails>(
        'cancellation_details', cancellationDetails);
    writer
        .writeEnumValue<WithSubscriptionExposedPostRequestBodyCollectionMethod>(
            'collection_method', collectionMethod, (e) => e?.value);
    writer.writeIntValue('days_until_due', daysUntilDue);
    writer.writeStringValue('default_payment_method', defaultPaymentMethod);
    writer
        .writeObjectValue<WithSubscriptionExposedPostRequestBodyDefaultSource>(
            'default_source', defaultSource);
    writer.writeObjectValue<
            WithSubscriptionExposedPostRequestBodyDefaultTaxRates>(
        'default_tax_rates', defaultTaxRates);
    writer.writeObjectValue<WithSubscriptionExposedPostRequestBodyDiscounts>(
        'discounts', discounts);
    writer.writeCollectionOfPrimitiveValues<String?>('expand', expand);
    writer.writeObjectValue<
            WithSubscriptionExposedPostRequestBodyInvoiceSettings>(
        'invoice_settings', invoiceSettings);
    writer.writeCollectionOfObjectValues<
        WithSubscriptionExposedPostRequestBodyItems>('items', items);
    writer.writeStringValue('metadata', metadata);
    writer.writeBoolValue('off_session', value: offSession);
    writer.writeObjectValue<
            WithSubscriptionExposedPostRequestBodyPauseCollection>(
        'pause_collection', pauseCollection);
    writer
        .writeEnumValue<WithSubscriptionExposedPostRequestBodyPaymentBehavior>(
            'payment_behavior', paymentBehavior, (e) => e?.value);
    writer.writeObjectValue<
            WithSubscriptionExposedPostRequestBodyPaymentSettings>(
        'payment_settings', paymentSettings);
    writer.writeObjectValue<
            WithSubscriptionExposedPostRequestBodyPendingInvoiceItemInterval>(
        'pending_invoice_item_interval', pendingInvoiceItemInterval);
    writer.writeEnumValue<
            WithSubscriptionExposedPostRequestBodyProrationBehavior>(
        'proration_behavior', prorationBehavior, (e) => e?.value);
    writer.writeIntValue('proration_date', prorationDate);
    writer.writeObjectValue<WithSubscriptionExposedPostRequestBodyTransferData>(
        'transfer_data', transferData);
    writer.writeObjectValue<WithSubscriptionExposedPostRequestBodyTrialEnd>(
        'trial_end', trialEnd);
    writer.writeBoolValue('trial_from_plan', value: trialFromPlan);
    writer
        .writeObjectValue<WithSubscriptionExposedPostRequestBodyTrialSettings>(
            'trial_settings', trialSettings);
  }
}
