// ignore_for_file: type=lint
import 'package:microsoft_kiota_abstractions/microsoft_kiota_abstractions.dart';
import './products_post_request_body_default_price_data.dart';
import './products_post_request_body_marketing_features.dart';
import './products_post_request_body_metadata.dart';
import './products_post_request_body_package_dimensions.dart';

/// auto generated
class ProductsPostRequestBody implements Parsable {
  ///  Whether the product is currently available for purchase. Defaults to `true`.
  bool? active;

  ///  Data used to generate a new [Price](https://docs.stripe.com/api/prices) object. This Price will be set as the default price for this product.
  ProductsPostRequestBodyDefaultPriceData? defaultPriceData;

  ///  The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
  String? description;

  ///  Specifies which fields in the response should be expanded.
  Iterable<String>? expand;

  ///  An identifier will be randomly generated by Stripe. You can optionally override this ID, but the ID must be unique across all products in your Stripe account.
  String? id;

  ///  A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
  Iterable<String>? images;

  ///  A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
  Iterable<ProductsPostRequestBodyMarketingFeatures>? marketingFeatures;

  ///  Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
  ProductsPostRequestBodyMetadata? metadata;

  ///  The product's name, meant to be displayable to the customer.
  String? name;

  ///  The dimensions of this product for shipping purposes.
  ProductsPostRequestBodyPackageDimensions? packageDimensions;

  ///  Whether this product is shipped (i.e., physical goods).
  bool? shippable;

  ///  An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all.This may be up to 22 characters. The statement description may not include `<`, `>`, `\`, `"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter. Only used for subscription payments.
  String? statementDescriptor;

  ///  A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
  String? taxCode;

  ///  A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal.
  String? unitLabel;

  ///  A URL of a publicly-accessible webpage for this product.
  String? url;

  /// Creates a new instance of the appropriate class based on discriminator value
  ///  [parseNode] The parse node to use to read the discriminator value and create the object
  static ProductsPostRequestBody createFromDiscriminatorValue(
      ParseNode parseNode) {
    return ProductsPostRequestBody();
  }

  /// The deserialization information for the current model
  @override
  Map<String, void Function(ParseNode)> getFieldDeserializers() {
    var deserializerMap = <String, void Function(ParseNode)>{};
    deserializerMap['active'] = (node) => active = node.getBoolValue();
    deserializerMap['default_price_data'] = (node) => defaultPriceData =
        node.getObjectValue<ProductsPostRequestBodyDefaultPriceData>(
            ProductsPostRequestBodyDefaultPriceData
                .createFromDiscriminatorValue);
    deserializerMap['description'] =
        (node) => description = node.getStringValue();
    deserializerMap['expand'] =
        (node) => expand = node.getCollectionOfPrimitiveValues<String>();
    deserializerMap['id'] = (node) => id = node.getStringValue();
    deserializerMap['images'] =
        (node) => images = node.getCollectionOfPrimitiveValues<String>();
    deserializerMap['marketing_features'] = (node) => marketingFeatures = node
        .getCollectionOfObjectValues<ProductsPostRequestBodyMarketingFeatures>(
            ProductsPostRequestBodyMarketingFeatures
                .createFromDiscriminatorValue);
    deserializerMap['metadata'] = (node) => metadata =
        node.getObjectValue<ProductsPostRequestBodyMetadata>(
            ProductsPostRequestBodyMetadata.createFromDiscriminatorValue);
    deserializerMap['name'] = (node) => name = node.getStringValue();
    deserializerMap['package_dimensions'] = (node) => packageDimensions =
        node.getObjectValue<ProductsPostRequestBodyPackageDimensions>(
            ProductsPostRequestBodyPackageDimensions
                .createFromDiscriminatorValue);
    deserializerMap['shippable'] = (node) => shippable = node.getBoolValue();
    deserializerMap['statement_descriptor'] =
        (node) => statementDescriptor = node.getStringValue();
    deserializerMap['tax_code'] = (node) => taxCode = node.getStringValue();
    deserializerMap['unit_label'] = (node) => unitLabel = node.getStringValue();
    deserializerMap['url'] = (node) => url = node.getStringValue();
    return deserializerMap;
  }

  /// Serializes information the current object
  ///  [writer] Serialization writer to use to serialize this model
  @override
  void serialize(SerializationWriter writer) {
    writer.writeBoolValue('active', value: active);
    writer.writeObjectValue<ProductsPostRequestBodyDefaultPriceData>(
        'default_price_data', defaultPriceData);
    writer.writeStringValue('description', description);
    writer.writeCollectionOfPrimitiveValues<String?>('expand', expand);
    writer.writeStringValue('id', id);
    writer.writeCollectionOfPrimitiveValues<String?>('images', images);
    writer.writeCollectionOfObjectValues<
            ProductsPostRequestBodyMarketingFeatures>(
        'marketing_features', marketingFeatures);
    writer.writeObjectValue<ProductsPostRequestBodyMetadata>(
        'metadata', metadata);
    writer.writeStringValue('name', name);
    writer.writeObjectValue<ProductsPostRequestBodyPackageDimensions>(
        'package_dimensions', packageDimensions);
    writer.writeBoolValue('shippable', value: shippable);
    writer.writeStringValue('statement_descriptor', statementDescriptor);
    writer.writeStringValue('tax_code', taxCode);
    writer.writeStringValue('unit_label', unitLabel);
    writer.writeStringValue('url', url);
  }
}
